# Disable specific checks
ParserBlockingScript:
  enabled: false

ValidSchema:
  enabled: false

DeprecateLazysizes:
  enabled: false

ImgWidthAndHeight:
  enabled: false

ContentForHeaderModification:
  enabled: false

# Enable specific checks
LiquidSyntax:
  enabled: true

# Set the severity level for specific checks
severity:
  ValidSchema: warning
  DeprecateLazysizes: warning
  ImgWidthAndHeight: warning
  ParserBlockingScript: warning
  ContentForHeaderModification: warning